apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmaker-parser-telegram-bot
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmaker_parser_telegram_bot
  template:
    metadata:
      labels:
        app: bookmaker_parser_telegram_bot
    spec:
      containers:
      - name: bookmaker-parser-telegram-bot
        image: lines14/bookmaker_parser_telegram_bot:latest
        envFrom:
        - configMapRef:
            name: configmap
        ports:
        - containerPort: 2226
      imagePullSecrets:
      - name: docker-credentials