apiVersion: v1
kind: Service
metadata:
  name: bookmaker-parser-telegram-bot
spec:
  type: NodePort
  ports:
  - port: 2226
    targetPort: 2226
    nodePort: 2226
  selector:
    app: bookmaker-parser-telegram-bot