apiVersion: v1
kind: Service
metadata:
  name: bookmaker-parser-telegram-bot
spec:
  type: ClusterIP
  ports:
  - name: svc-port
    port: 81
    targetPort: app-port
    protocol: TCP
  selector:
    app: bookmaker-parser-telegram-bot
