name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: actions
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_IMAGE }} .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_IMAGE }}